#30
alisabox/aleksandrbelov.ru pull request #31
Opened 2021-11-22 17:35 UTC by RomanRid

#30

2021-11-22 17:35 UTC, RomanRid commented
#30

2021-11-23 02:55 UTC, alisabox requested changes

2021-11-23 02:55 UTC, alisabox commented on styles/style.css
> +  grid-template-columns: 1fr 1fr;
Лучше сделать grid-template-rows: 1fr 1fr здесь, т.к. на экране мобильного текст и карта не будут влезать в 2 колонки.
Только нужно будет переопределить grid-template-rows на auto для большей ширины экрана в @media (min-width: 768px)

2021-11-23 02:55 UTC, alisabox commented on styles/style.css
> +  .train__container {
Добавь, пожалуйста, стили к существующему селектору .train__container, чтобы не было дублирования.
display: grid уже определен у тебя для .train__container выше, он будет применяться для всех разрешений экрана. Дублировать не нужно, напротив, лучше удалить здесь и в @media (min-width: 1200px) для этого класса.

2021-11-23 02:55 UTC, alisabox commented on styles/style.css
>      display: grid;
Аналогично, если стили display, grid-template-columns, column-gap определены для меньшего разрешения экрана и не меняются, то лучше убрать здесь. Они будут автоматически применяться для больших разрешений.

2021-11-24 16:48 UTC, RomanRid commented
Алиса, я исправил. Посмотрите, как это отображается на устройствах.
![photo5256248665985627815](https://user-images.githubusercontent.com/89779144/143280278-f7a04641-174c-42a4-94bc-2a824853667f.jpg)
![photo5256248665985627811](https://user-images.githubusercontent.com/89779144/143280285-7694a0b7-6d74-447d-ae52-e2cf5a02d312.jpg)
![photo5256248665985627810](https://user-images.githubusercontent.com/89779144/143280290-d172f9f0-74e1-4d18-92e8-3a5e7a3b788a.jpg)

2021-11-24 16:49 UTC, RomanRid commented on styles/style.css
>      display: grid;
Исправил, прошу проверить.

2021-11-25 00:05 UTC, alisabox commented
Роман, отлично, спасибо!

2021-11-25 00:05 UTC, merged